% Script to run Driver generated by facile.pl
clear all; 
testMatlabDriver; 
figure(1); plot(t, S0); title('S0');
figure(2); plot(t, S1); title('S1');
figure(3); plot(t, A); title('A');
figure(4); plot(t, B); title('B');
figure(5); plot(t, C); title('C');
figure(6); plot(t, D); title('D');
figure(7); plot(t, E); title('E');
figure(8); plot(t, F); title('F');
figure(9); plot(t, G); title('G');
figure(10); plot(t, X); title('X');
figure(11); plot(t, Y); title('Y');
figure(12); plot(t, W); title('W');
figure(13); plot(t, Z); title('Z');

% Sample values of outputs for future reference
disp('S0= '); disp([S0(1) S0(100) S0(200) S0(end)]);
disp('S1= '); disp([S1(1) S1(100) S1(200) S1(end)]);
disp('A= '); disp([A(1) A(100) A(200) A(end)]);
disp('B= '); disp([B(1) B(100) B(200) B(end)]);
disp('C= '); disp([C(1) C(100) C(200) C(end)]);
disp('D= '); disp([D(1) D(100) D(200) D(end)]);
disp('E= '); disp([E(1) E(100) E(200) E(end)]);
disp('F= '); disp([F(1) F(100) F(200) F(end)]);
disp('G= '); disp([G(1) G(100) G(200) G(end)]);
disp('X= '); disp([X(1) X(100) X(200) X(end)]);
disp('Y= '); disp([Y(1) Y(100) Y(200) Y(end)]);
disp('w= '); disp([W(1) W(100) W(200) Y(end)]);
disp('Z= '); disp([Z(1) Z(100) Z(200) Z(end)]);

