% Script to run Driver generated by facile.pl
clear all; 
testMatlab_miscDriver; 
figure(1); plot(t, X); title('X');

% Sample values of outputs for future reference
disp('S0= '); disp([X(1) X(10) X(20) X(end)]);
