% Script to run Driver generated by facile.pl
clear all; 
steady_stateDriver; 
figure(1); plot(t, y); title('X, Y and Z');

disp('Sample values of outputs for future reference:');
disp('X= '); disp([X(1) X(50) X(400) X(end)]);
disp('Y= '); disp([Y(1) Y(50) Y(400) Y(end)]);
disp('Z= '); disp([Z(1) Z(50) Z(400) Z(end)]);

t_event1 = find(t == event_times(1));
t_event2 = find(t == event_times(2));
t_event3 = find(t == event_times(3));
t_event4 = find(t == event_times(4));
t_event5 = find(t == event_times(5));
t_event6 = find(t == event_times(6));
t_event7 = find(t == event_times(7));

disp('Value of X,Y and Z at event times');
event_times
disp('X= '); disp(X([t_event1,t_event2,t_event3,t_event4,t_event5,t_event6,t_event7])');
disp('Y= '); disp(Y([t_event1,t_event2,t_event3,t_event4,t_event5,t_event6,t_event7])');
disp('Z= '); disp(Z([t_event1,t_event2,t_event3,t_event4,t_event5,t_event6,t_event7])');

